version: 2

python:
  install:
    - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - cd chipyard && git submodule update --init --force generators/dsagen2 && cd ..

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

submodules:
  recursive: false
  include:
     - docs
     - chipyard
     - dsa-scheduler


