version: 2

python:
  version: "3.7"
  install:
    - breathe

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

submodules:
  recursive: true
  exclude:
     - dsa-llvm-project
     - riscv-gnu-toolchain
     - chipyard
     - dsa-gem5

