version: 2

python:
  install:
    - requirements: docs/requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

submodules:
  recursive: false
  include:
     - docs
     - dsa-scheduler


