version: 2

build:
  jobs:
    post_install:
      - cd chipyard && git submodule update --init --force generators/dsagen2 && cd ..

python:
  version: "3.7"
  install:
    - requirements: docs/requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

submodules:
  recursive: false
  include:
     - docs
     - chipyard
     - dsa-scheduler


