version: 2

python:
  version: "3.7"
  install:
    - requirements: docs/requirements.txt

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

submodules:
  recursive: false
  include:
     - dsagen2
  exclude:
     - dsa-llvm-project
     - riscv-gnu-toolchain
     - dsa-gem5