version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

submodules:
  recursive: true
  exclude:
     - dsa-llvm-project
     - riscv-gnu-toolchain
     - dsa-gem5

