prefix=/usr/local
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
libdir=${exec_prefix}/lib
includedir=${prefix}/include
ARCH=X86
SYS=LINUX
CC=gcc
CFLAGS=-O4  -Wall -I. -DHAVE_MALLOC_H -D_GNU_SOURCE -DARCH_X86 -DSYS_LINUX -DHAVE_PTHREAD -s
ALTIVECFLAGS=
LDFLAGS= -lm -lpthread -s
AR=ar
RANLIB=ranlib
STRIP=strip
AS=
ASFLAGS= -O2 -f elf
EXE=
VIS=
HAVE_GETOPT_LONG=1
DEVNULL=/dev/null
PLATFORM=CPU
